baseurl = "https://crowdersoup.com/"
languageCode = "en-us"
title = "CrowderSoup"
theme = "basics-plus"
disqusShortname = "aaroncrowder"

[params]
    author = "Aaron Crowder"
    github = "CrowderSoup"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    title = "home page"
    url = "/"
    weight = -110 # Ensure "Home" page is first
	[[menu.main]]
		identifier = "about"
		name = "About"
		title = "about page"
		url = "/about/"
		weight = -109 # Ensure "About" page is second
	[[menu.main]]
		identifier = "GitHub"
		name = "GitHub"
		title = "GitHub Profile"
		url = "https://github.com/CrowderSoup"
		weight = 1
	[[menu.main]]
		identifier = "Twitter"
		name = "Twitter"
		title = "Twitter Profile"
		url = "https://twitter.com/CrowderSoup"
		weight = 2
	[[menu.main]]
		identifier = "Mastodon"
		name = "Mastodon"
		title = "Mastodon Profile"
		url = "https://socialmast.xyz/@CrowderSoup"
		weight = 3
