baseurl = "https://crowdersoup.com/"
languageCode = "en"
title = "CrowderSoup"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/CrowderSoup\">Aaron Crowder</a> 2018"
disqusShortname = "aaroncrowder"
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true

publishDir = "docs"

[params.assets]
customCSS = ["css/custom.css"]

[params.rss]
includeContent = true # Includes whole content in rss
authorName = "Aaron Crowder" # Site author's full name
authorEmail = "aaron.crowder@gmail.com"

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "CrowderSoup" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles


[params.social]
twitter = "CrowderSoup"
github = "CrowderSoup"
email = "aaron.crowder@gmail.com"

[params.social.config]
platforms = ["twitter","github","email"]

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

